In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3, 4, 5,7,8,9]
arr = np.array(my_list)
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr 

array([1, 2, 3, 4, 5, 7, 8, 9])

In [6]:
arr[0] + arr[2]

4

In [7]:
matriz 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
matriz[0,2]
# de esta manera podemos escojer un valor de fila y posicion 

3

In [9]:
arr 

array([1, 2, 3, 4, 5, 7, 8, 9])

In [10]:
arr[1:6]
# para tomar los valores de una fila podemos usar : que indica un rango

array([2, 3, 4, 5, 7])

In [11]:
arr[:6]
# aqui toma desde la posicion 0

array([1, 2, 3, 4, 5, 7])

In [12]:
arr[2:]
# aqui toma desde la posicion 2 hasta el ultimo

array([3, 4, 5, 7, 8, 9])

In [13]:
arr

array([1, 2, 3, 4, 5, 7, 8, 9])

In [14]:
arr[::3]

# aqui empiesa por posicion 0 luego cuenta 3 posiciones y agarra ese numero

array([1, 4, 8])

In [15]:
arr[-1]
# toma el ultimo numro de la lista o los toma en reversa

9

In [16]:
arr[-3]

7

In [17]:
matriz
'''
array([[1, 2, 3],      fila '0'
       [4, 5, 6],      fila '1'
       [7, 8, 9]])     fila '2'
'''

"\narray([[1, 2, 3],      fila '0'\n       [4, 5, 6],      fila '1'\n       [7, 8, 9]])     fila '2'\n"

In [18]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [19]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [20]:
matriz_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
matriz_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
matriz_3d[1:,:,1:]

array([[[ 8,  9],
        [11, 12]]])