In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])
arr.dtype
# necesitamos para un mejor uso datos como en redes neuronales tipo float

dtype('int64')

In [4]:
# de esta maneta el array se vuelve float
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

podemos volver facilmente cualquier array en cualquier tipo de datos 
con arr.astype(np.<tipo de dato>)


In [5]:
arr

array([1., 2., 3., 4.])

In [6]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.float64)
arr

array([0., 1., 2., 3., 4.])

In [7]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [8]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [9]:
arr = np.array(['hola,'0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

SyntaxError: unterminated string literal (detected at line 1) (134414359.py, line 1)