In [2]:
import numpy as np

In [5]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [12]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [13]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [14]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

## agreagar o eliminar dimensiones 


In [15]:
# de esta manera puedes generar la cantidad de dimensiones que le das
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [18]:
# de esta manera puedes expandir la dimencion con np.expand_dims
# axis 0 son filas axis 1 son columnas 
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [20]:
# esto comprime al numero de dimensines que se deben de utilizar np.squeeze
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


In [31]:
hundred_dimension = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],ndmin=32)
print(hundred_dimension)
hundred_dimension.ndim

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ 1  2  3]
                               [ 4  5  6]]

                              [[ 7  8  9]
                               [10 11 12]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


32

In [67]:
hundred_dimension = np.expand.dims(([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]), axis= 0)
print(hundred_dimension)
hundred_dimension.ndim

AttributeError: module 'numpy' has no attribute 'expand'

In [39]:
1 ✅ np.arange (Start,Ens,Steps) → es como el list( range(0,10)) pero como arrange
2 ✅ np.zeros(n)
3 ✅ np.ones(n)
4 ✅ np.linspace(Start, End, evenly spaced samples over interval Space and End)
5 ✅ np.eye(n) ·· Matriz identidad

Arrays con numeros randoms

☑️ np.random.rand(Filas, Columnas, mas dimensiones ) ·· Ambos con numeros randoms
☑️ np.random.randint(Start, End, cantidad de caracteres) ·· N random entre Start y End y tupla dims

SyntaxError: invalid character '✅' (U+2705) (842004469.py, line 1)

In [66]:
enteros_aleatorios = np.random.randint(0, 100, size=(1, 1, 3))
print(enteros_aleatorios)
# ☑️ np.random.randint(Start, End, cantidad de caracteres(Filas, Columnas, numero de caracteres)) 
# para numeros enteros aleatorios 

[[[56 51 86]]]
