In [1]:
import numpy as np

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
# de esta forma puedes crear un array de un rango que quieras 
# numpy.arange(start,stop, step), dtype=None)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# Nos permite definir estructuras o esquemas
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
# define un inicio, un final y cuantas divisiones tendrá.
np.linspace(0,100,100)

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(4,2,2)

array([[[0.33390858, 0.79908778],
        [0.15057735, 0.50941876]],

       [[0.59961104, 0.09773378],
        [0.52830759, 0.81514639]],

       [[0.54597255, 0.51264235],
        [0.02873174, 0.05789341]],

       [[0.50989169, 0.01044474],
        [0.80666935, 0.59291283]]])

In [23]:
enteros_aleatorios = np.random.randint(0, 100, size=(1, 1, 3))
print(enteros_aleatorios)
# ☑️ np.random.randint(Start, End, cantidad de caracteres(Filas, Columnas, numero de caracteres)) 
# para numeros enteros aleatorios 

[[[54 38 78]]]


In [35]:
np.random.randint(1,100,(10,10))

array([[15, 78, 45, 48, 58, 31,  3, 50, 13, 16],
       [83, 96,  4, 67, 28, 96, 69, 73, 15, 52],
       [13, 44,  4, 36, 35,  5, 28, 59, 27, 57],
       [15, 93, 26, 17, 32, 96, 34, 92, 75, 63],
       [ 7, 72, 51, 98, 71, 60, 36, 97, 44, 19],
       [40, 21,  7, 55, 25, 95, 24, 88, 45, 65],
       [34, 41, 22, 30, 25, 19, 11, 84, 49, 55],
       [23, 92, 90, 69, 88, 87, 95, 33, 37, 90],
       [61, 61, 79, 11, 83,  1, 96, 85, 90, 59],
       [82, 92, 73, 91, 66, 37, 13, 65, 59, 69]])

In [36]:
# con un numero predeterminado
matriz= np.full((3,3),7)
matriz

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])