In [16]:
import numpy as np

In [31]:
arr = np.random.randint(1,10,(3,2))
arr

array([[8, 1],
       [5, 9],
       [4, 2]])

In [30]:
# te da la forma en que esta el array
arr.shape

(2, 3)

tienes que respetar la forma original del array en este caso solo se puede por numeros que multiplicados me den 6 ya que es el tamaño del array 


In [33]:
# reorganiza el array ala forma que tu quieras
arr.reshape(2,3)

array([[8, 1, 5],
       [9, 4, 2]])

In [34]:
np.reshape(arr,(1,6))

array([[8, 1, 5, 9, 4, 2]])

In [35]:
arr

array([[8, 1],
       [5, 9],
       [4, 2]])

In [36]:
# en c toma los datos por filas 
np.reshape(arr,(2,3),'C')

array([[8, 1, 5],
       [9, 4, 2]])

In [37]:
# en f toma los datos por columnas
np.reshape(arr,(2,3),'F')

array([[8, 4, 9],
       [5, 1, 2]])

In [38]:
# de esta manera elige la mejor optimizacion de timepo
# pero lo mejor es usar el lenguaje c
np.reshape(arr,(2,3),'A')

array([[8, 1, 5],
       [9, 4, 2]])

In [65]:
uwu = np.arange(0,24)
arr_uwu = np.array(uwu)
arr_uwu_reshaped = np.reshape(arr_uwu, (4, 6))
print(arr_uwu_reshaped)
shape_uwu = arr_uwu_reshaped.shape
print(shape_uwu)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


In [66]:
np.reshape(arr_uwu,(2,12),'C')


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])