In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,20,10)
print(arr)

[ 4  3  5 12 15  9  9  8  5 10]


In [4]:
matriz = arr.reshape(2,5)
print(matriz)

[[ 4  3  5 12 15]
 [ 9  9  8  5 10]]


In [5]:
arr

array([ 4,  3,  5, 12, 15,  9,  9,  8,  5, 10])

In [6]:
# retorna el numero mayor que tenemos de nuestro array 
arr.max()

15

In [7]:
matriz

array([[ 4,  3,  5, 12, 15],
       [ 9,  9,  8,  5, 10]])

In [8]:
# con 0 te da el valor mas alto por columna 
# con 1 te da el valor mas alto por fila 
matriz.max(0)


array([ 9,  9,  8, 12, 15])

In [9]:
# nos da el numero de la posicion donde se encuentra el numero mas grande de nuestra array
print(arr)
arr.argmax()

[ 4  3  5 12 15  9  9  8  5 10]


4

In [10]:
print(matriz)
matriz.argmax()

[[ 4  3  5 12 15]
 [ 9  9  8  5 10]]


4

In [11]:
# retorna el numero menor que tenemos en nuestra array 
arr.min()

3

In [12]:
# retorna el numero menor que tenemos en nuestra array 
matriz.min()

3

In [13]:
# retorna la posicion del numero menor en la array 
arr.argmin()

1

In [14]:
matriz.argmin()

1

In [15]:
arr

array([ 4,  3,  5, 12, 15,  9,  9,  8,  5, 10])

In [16]:
# nos dice cuantos numeros hay entre el numero mas pequeño al mas grande como una resta 
arr.ptp()

12

In [17]:
matriz

array([[ 4,  3,  5, 12, 15],
       [ 9,  9,  8,  5, 10]])

In [18]:
# con 0 te da el valor mas alto por columna 
# con 1 te da el valor mas alto por fila 
print(matriz)
print("*" * 10)
columna = matriz.ptp(0)
print(columna) # en columna se suma y se divide entre dos 
fila = matriz.ptp(1) 
print(fila) # en fila se resta el mas grande por el mas pequeño 

[[ 4  3  5 12 15]
 [ 9  9  8  5 10]]
**********
[5 6 3 7 5]
[12  5]


In [19]:
arr.sort()
arr

array([ 3,  4,  5,  5,  8,  9,  9, 10, 12, 15])

In [20]:
# 50 cual es el valor que se encuentra en la mitad esto es la mediana 
# 0 el numero mas bajo
# 100 el valor mas alto 
np.percentile(arr,50)

8.5

In [21]:
# esto es la mediana
np.median(arr)

8.5

In [22]:
np.median(matriz,0)

array([ 6. ,  6.5,  7.5,  8.5, 11.5])

In [23]:
# esto es la desviasion estandar 
np.std(arr)

3.605551275463989

In [24]:
# esto es la varianza 
np.var(arr)

13.0

In [25]:
# esto es la media
np.mean(arr)

8.0

In [26]:
a = np.array([[1,2],[3,4]]) #2 dimenciones
b = np.array([5,6]) #1 dimension


In [27]:
b = np.array(b, ndmin=2)
b.ndim

2

In [28]:
# de esta maneta puedes concatenar los arrays de misma dimension en filas 
# para cambiar una dimension de un array usa np.array(#, ndmin=#) 
# no use expand porque se expande cada vez que se ejecuta?
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
# de esta maneta puedes concatenar los arrays de misma dimension en columnas 
np.concatenate((a,b.T), axis = 1)


array([[1, 2, 5],
       [3, 4, 6]])

In [30]:
b.T
# esto es una transpuesta de dimensiones 

array([[5],
       [6]])

In [31]:

b = np.array([[1, 2, 3], [4, 5, 6]])
b_transpose = b.T

print("b:")
print(b)

print("b transpuesta:")
print(b_transpose)

b:
[[1 2 3]
 [4 5 6]]
b transpuesta:
[[1 4]
 [2 5]
 [3 6]]


In [32]:


a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
column_sums = np.sum(a, axis=0)

print("Matriz a:")
print(a)

print("Suma de columnas de la matriz a:")
print(column_sums)

Matriz a:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Suma de columnas de la matriz a:
[12 15 18]


In [33]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_sums = np.sum(a, axis=1)

print("Matriz a:")
print(a)

print("Suma de filas de la matriz a:")
print(row_sums)

Matriz a:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Suma de filas de la matriz a:
[ 6 15 24]
