In [1]:
import numpy as np

siempre que quieras sacar trozos de un array usa copy

.copy() nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original.

In [3]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [5]:
trozo_de_arr = arr[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [6]:
trozo_de_arr[:] = 0 
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [7]:
# cualquier cambio que ocurra le ocurre al original
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [11]:
# para eso es copy nos salva de no modificar el array original
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [12]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])