In [5]:
import numpy as np

todo lo que quieras condicionar va adentro de los parentesis 

In [6]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [7]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [8]:
# esta es la sintaxis para que te devuelva la condicion en no boleanos 
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [9]:
# esta es otra manera
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [10]:
arr[arr>5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [11]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)

In [12]:
# Otra funcion muy util de numpy tambien es
# np.where(condicion, valor si, valor si la condicion no se cumple)
matriz = np.array([[19,  4, 43], [ 8, 96, 80], [ 6, 99, 35]])
np.where(matriz > 50, 0, 1)

array([[1, 1, 1],
       [1, 0, 0],
       [1, 0, 1]])

recuerda que para una condicion de arrays tiene que estar adentro de 
corchetes 

In [15]:
mua = np.linspace(1,50,50, dtype='int16')
mua[mua%2!=0]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49], dtype=int16)

In [16]:
mua[mua%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50], dtype=int16)