In [23]:
import numpy as np 

In [24]:
lista = [1,2]
lista 

[1, 2]

In [25]:
# multiplica los datos como si los copiara  
lista * 2

[1, 2, 1, 2]

In [26]:
arr = np.arange(0,10)
arr2 = arr.copy()

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# en los array si funciona multiplicar por 2 cada variable 
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
arr +2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
1/ arr

/tmp/ipykernel_386/3009366600.py:1: RuntimeWarning: divide by zero encountered in divide
  1/ arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [31]:
arr **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [32]:
# se suma cada posicion con sigo mismo con cualquier operacion 
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
# se suman en su posiciones respectivas
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

producto punto 

In [36]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [37]:
# https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:multiplying-matrices-by-matrices/v/multiplying-a-matrix-by-a-matrix
# multiplicacion de producto punto 

In [38]:
matriz


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [40]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

In [41]:


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)

print(dot_product)

32


In [42]:
'''
En este caso, los vectores a y b tienen la misma longitud y están definidos 
como a = [1, 2, 3] y b = [4, 5, 6]. Para calcular el producto punto de estos 
dos vectores, primero se realiza la multiplicación elemento a elemento 
entre a y b, lo que resulta en otro vector [4, 10, 18]. 
Luego, se suman los elementos de este vector para obtener el producto punto,
que es igual a 32.

es 1 * 4, 2 * 5 , 3 * 6  luego se suman 
'''

'\nEn este caso, los vectores a y b tienen la misma longitud y están definidos \ncomo a = [1, 2, 3] y b = [4, 5, 6]. Para calcular el producto punto de estos \ndos vectores, primero se realiza la multiplicación elemento a elemento \nentre a y b, lo que resulta en otro vector [4, 10, 18]. \nLuego, se suman los elementos de este vector para obtener el producto punto,\nque es igual a 32.\n\nes 1 * 4, 2 * 5 , 3 * 6  luego se suman \n'

In [43]:
# con esta operación quitaremos los valores repetidos de nuestro array.
# Lo mas increíble es que se pueden hacer algunas operaciones extras 
# como lo es “Sabes cuantas veces se repiten dichos datos” 
# (Hay varias operaciones extras que puede retornar).
# Creamos un array con valores duplicados
a = np.array([1, 2, 3, 2, 4, 1, 3, 5])

# Encontramos los valores únicos en el array
unique_values = np.unique(a)

print(unique_values)


[1 2 3 4 5]


In [44]:
# Creamos un array con valores duplicados
a = np.array([1, 2, 3, 2, 4, 1, 3, 5])

# Encontramos los valores únicos y sus frecuencias
unique_values, value_counts = np.unique(a, return_counts=True)

# Imprimimos los valores únicos y sus frecuencias
for value, count in zip(unique_values, value_counts):
    print(f"{value} se repite {count} veces.")

1 se repite 2 veces.
2 se repite 2 veces.
3 se repite 2 veces.
4 se repite 1 veces.
5 se repite 1 veces.
